create table tblusers(
clocknumber integer not null,
lastname varchar (15),
firstname varchar (15),
inactive varchar(5) Default 'False',
streetaddress varchar(100) not null,
city varchar(30) not null,
countycode varchar(2) not null,
state varchar(2) not null,
zipcode varchar(5) not null,
payrate decimal(4,2) not null,
hiredate date not null,
dependants int default '1',
healthIns Decimal(5,2),
visionIns Decimal(5,2),
dentalIns Decimal(5,2),
lifeIns Decimal(5,2),
primary key (clocknumber));
